version: "3.9.5"

services:
    starlink-access:
        container_name: "Starlink-Access-App"
        image: finkurniawan/starlink-access
        ports:
            - 8080:8080
        environment:
           POSTGRE_DB_URL: "jdbc:postgresql://postgres:5432/starlink_access"
           POSTGRE_DB_USERNAME: "postgres"
           POSTGRE_DB_PASSWORD: "postgres"
           JWT_SECRET: "secret"
           JWT_ACCESS_TOKEN_EXPIRATION: "3600"
           JWT_REFRESH_TOKEN_EXPIRATION: "86400"
        depends_on:
            - postgres

    postgres:
        container_name: "PostgreSQL-Database"
        image: postgres
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=starlink_access
